services:
  github_runner:
    # Dockerfileが存在するカレントディレクトリをビルドコンテキストとして指定
    build: 
      context: ./self_host_runner
      dockerfile: .build/Dockerfile
    volumes:
      - runner_vol_x:/home/runner
      # - gemini_auth:${ROOT:-/root}/.gemini
      - gemini_auth:/home/runner/.config/gcloud
    # .env ファイルから環境変数を読み込みます
    env_file:
      - .env
      - .env.runner_x
    # コンテナを再起動するポリシー（任意）
    # always: 常に再起動
    # unless-stopped: 明示的に停止しない限り再起動
    restart: unless-stopped

volumes:
  gemini_auth:
    name: shared_gemini_auth
  runner_vol_x:
  